name: Official RK3588 Image (5.10.66)

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

env:
  TZ: America/New_York
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  kdevbuild:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - set_vendor: armbian
            set_rootfs: armbian_bookworm_gnome_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_bookworm_mini_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_bookworm_xfce_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_bullseye_mini_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_forky_gnome_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_forky_mini_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_forky_xfce_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_jammy_gnome_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_jammy_mini_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_jammy_xfce_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_noble_gnome_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_noble_mini_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_noble_xfce_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_plucky_gnome_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_plucky_mini_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_plucky_xfce_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_trixie_gnome_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_trixie_mini_aarch64.rar
          - set_vendor: armbian
            set_rootfs: armbian_trixie_xfce_aarch64.rar

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show environment
        id: basic_info
        run: |
          nproc
          uname -a
          cat /etc/*release
          free -h
          mount
          df -h
          cat /proc/cpuinfo
          cat /proc/meminfo

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th

      - name: Run build in Ubuntu 22.04 container
        working-directory: /builder
        run: |
          pwd
          sudo /bin/cp -a ${{ github.workspace }}/* .
          ls -alh
          sudo docker run --rm \
            --privileged \
            --cap-add SYS_ADMIN \
            -v /dev:/dev \
            -v /builder:/workspace \
            -w /workspace \
            -e set_vendor=${{ matrix.set_vendor }} \
            -e set_rootfs=${{ matrix.set_rootfs }} \
            ubuntu:22.04 \
            bash -c "
              chmod +x /workspace/kdevbuild/rk3588-image-official-k5.10.66.sh ;
              /workspace/kdevbuild/rk3588-image-official-k5.10.66.sh
            "

      - name: List build output
        run: |
          ls -alh  /builder/release/*
          md5sum /builder/release/*

      - name: Upload Image to Release
        uses: ncipollo/release-action@main
        with:
          tag: RK3588-Image-k5.10.66
          artifacts: /builder/release/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: | # RK3588-Image-k5.10.66 (Official)

            ## 系统密码

            - 用户名: root   密码: admin
            - 用户名: admin  密码: admin

            ## 镜像使用指引(文件后缀为rockdev.rar)

            解压后打开RKDevTool.exe，选择'下载镜像'，点击'执行'即可

            ```
            RKDevTool/
            ├── bin
            │         ├── adb.exe
            │         ├── AdbWinApi.dll
            │         ├── AdbWinUsbApi.dll
            │         ├── AFPTool.exe
            │         └── RKImageMaker.exe
            ├── config.cfg
            ├── config.ini
            ├── Language
            │         ├── Chinese.ini
            │         └── English.ini
            ├── RKDevTool.exe
            └── rockdev
                └── image
                    ├── boot.img
                    ├── MiniLoaderAll.bin
                    ├── modules.tar.gz
                    ├── package-file
                    ├── parameter.txt
                    ├── rootfs.img
                    └── uboot.img
            ```

            ## 免责声明

            - **按原样提供**：镜像不作任何保证，使用风险自负
            - **无官方关联**：与深圳亮钻科技有限公司无官方关系
            - **安全提示**：请及时更新补丁、修改默认密码、配置防火墙


